development:
  dialect: postgres
  datasource: dbname=development sslmode=disable user=development password=development host=localhost port=5434
  dir: migrations
  table: migrations

staging:
  dialect: postgres
  datasource: dbname=${PG_DATABASE} sslmode=disable user=${PG_USER} password=${PG_PASSWORD} host=${PG_HOST} port=${PG_PORT}
  dir: migrations
  table: migrations
